models/Bumdes.php
<?php

namespace app\models;

use Yii;
use \app\models\base\Bumdes as BaseBumdes;

/**
 * This is the model class for table "tb_bumdes".
 */
class Bumdes extends BaseBumdes
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['nama_bumdes', 'nama_desa', 'alamat', 'no_perdes', 'th_perdes'], 'required'],
            [['alamat'], 'string'],
            [['th_perdes'], 'integer'],
            [['jml_omset_th', 'kontribusi_pen_desa', 'jml_modal', 'jml_modal_lain', 'jml_kas', 'jml_aset_lcr', 'jml_aset_ttp', 'jml_utang', 'jml_utang_bank', 'jml_unit_ush'], 'number'],
            [['kode_bumdes'], 'string', 'max' => 20],
            [['nama_bumdes', 'nama_desa', 'no_perdes'], 'string', 'max' => 200],
            [['adart', 'rencana_men', 'rencana_th', 'sop', 'catatan_keu'], 'string', 'max' => 1],
            [['status'], 'string', 'max' => 4],
            [['kode_kabupaten', 'kode_kecamatan'], 'string', 'max' => 100],
            // [['lock'], 'default', 'value' => '0'],
            // [['lock'], 'mootensai\components\OptimisticLockValidator']
        ]);
    }
	
}

controllers/BumdesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Bumdes;
use app\models\BumdesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BumdesController implements the CRUD actions for Bumdes model.
 */
class BumdesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Bumdes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BumdesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Bumdes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $providerMasalahBumdes = new \yii\data\ArrayDataProvider([
            'allModels' => $model->masalahBumdes,
        ]);
        $providerUnitBumdes = new \yii\data\ArrayDataProvider([
            'allModels' => $model->unitBumdes,
        ]);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'providerMasalahBumdes' => $providerMasalahBumdes,
            'providerUnitBumdes' => $providerUnitBumdes,
        ]);
    }

    /**
     * Creates a new Bumdes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Bumdes();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id_bumdes]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Bumdes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id_bumdes]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Bumdes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->deleteWithRelated();

        return $this->redirect(['index']);
    }

    
    /**
     * Finds the Bumdes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Bumdes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bumdes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
    * Action to load a tabular form grid
    * for MasalahBumdes
    * @author Yohanes Candrajaya <moo.tensai@gmail.com>
    * @author Jiwantoro Ndaru <jiwanndaru@gmail.com>
    *
    * @return mixed
    */
    public function actionAddMasalahBumdes()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('MasalahBumdes');
            if (!empty($row)) {
                $row = array_values($row);
            }
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('_action') == 'load' && empty($row)) || Yii::$app->request->post('_action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formMasalahBumdes', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
    * Action to load a tabular form grid
    * for UnitBumdes
    * @author Yohanes Candrajaya <moo.tensai@gmail.com>
    * @author Jiwantoro Ndaru <jiwanndaru@gmail.com>
    *
    * @return mixed
    */
    public function actionAddUnitBumdes()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('UnitBumdes');
            if (!empty($row)) {
                $row = array_values($row);
            }
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('_action') == 'load' && empty($row)) || Yii::$app->request->post('_action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formUnitBumdes', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionKecamatan() 
    {
        
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $cat_id = end($_POST['depdrop_parents']);
            $list = \app\models\Kecamatan::find()
            ->where(['kd_kab'=>$cat_id])
            ->select(['kd_kec','nama_kec'])->asArray()->all();
            // $selected  = null;
            $selected_id = $_POST['depdrop_all_params']['selected_id']; 
            if ($cat_id != null && count($list) > 0) {
                // $selected = '';
                foreach ($list as $i => $row) {
                    $out[] = ['id' => $row['kd_kec'], 'name' => $row['nama_kec']];
                    // if ($i == 0) {
                    //     $selected = $row['kd_kec'];
                    // }
                }
            // Shows how you can preselect a value
                return ['output' => $out, 'selected' => $selected_id];
            }
        }
        return ['output' => '', 'selected' => ''];
    }
}

views/bumdes/_dataMasalahBumdes.php
<?php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

    $dataProvider = new ArrayDataProvider([
        'allModels' => $model->masalahBumdes,
        'key' => function($model){
            return ['id_bumdes' => $model->id_bumdes, 'id_masalah' => $model->id_masalah];
        }
    ]);
    $gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        [
                'attribute' => 'masalah.nama_masalah',
                'label' => 'Masalah'
            ],
        [
            'class' => 'app\widgets\grid\ActionColumn',
            'controller' => 'masalah-bumdes'
        ],
    ];
    
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'],
        'pjax' => true,
        'beforeHeader' => [
            [
                'options' => ['class' => 'skip-export']
            ]
        ],
        'export' => [
            'fontAwesome' => true
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'persistResize' => false,
    ]);

views/bumdes/_dataUnitBumdes.php
<?php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

    $dataProvider = new ArrayDataProvider([
        'allModels' => $model->unitBumdes,
        'key' => function($model){
            return ['id_bumdes' => $model->id_bumdes, 'id_unit' => $model->id_unit];
        }
    ]);
    $gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        [
                'attribute' => 'unit.nama_unit',
                'label' => 'Unit'
            ],
        [
            'class' => 'app\widgets\grid\ActionColumn',
            'controller' => 'unit-bumdes'
        ],
    ];
    
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'],
        'pjax' => true,
        'beforeHeader' => [
            [
                'options' => ['class' => 'skip-export']
            ]
        ],
        'export' => [
            'fontAwesome' => true
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'persistResize' => false,
    ]);

views/bumdes/_detail.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Bumdes */

?>
<div class="bumdes-view">

    <div class="row">
        <div class="col-sm-9">
            
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        // 'id_bumdes',
        // 'kode_bumdes',
        // 'nama_bumdes',
        // 'nama_desa',
        // 'alamat:ntext',
        // 'no_perdes',
        // 'th_perdes',
        'adart',
        'rencana_men',
        'rencana_th',
        'sop',
        'catatan_keu',
        'jml_omset_th',
        'kontribusi_pen_desa',
        'jml_modal',
        'jml_modal_lain',
        'jml_kas',
        'jml_aset_lcr',
        'jml_aset_ttp',
        'jml_utang',
        'jml_utang_bank',
        'jml_unit_ush',
        'status',
        'kode_kabupaten',
        [
            'attribute' => 'kodeKecamatan.nama_kec',
            'label' => 'Kecamatan',
        ],
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>

views/bumdes/_expand.php
<?php
use yii\helpers\Html;
use kartik\tabs\TabsX;
use yii\helpers\Url;
$items = [
    [
        'label' => '<i class="glyphicon glyphicon-book"></i> '. Html::encode('Bumdes'),
        'content' => $this->render('_detail', [
            'model' => $model,
        ]),
    ],
        [
        'label' => '<i class="glyphicon glyphicon-book"></i> '. Html::encode('Masalah Bumdes'),
        'content' => $this->render('_dataMasalahBumdes', [
            'model' => $model,
            'row' => $model->masalahBumdes,
        ]),
    ],
                    [
        'label' => '<i class="glyphicon glyphicon-book"></i> '. Html::encode('Unit Bumdes'),
        'content' => $this->render('_dataUnitBumdes', [
            'model' => $model,
            'row' => $model->unitBumdes,
        ]),
    ],
        ];
echo TabsX::widget([
    'items' => $items,
    'position' => TabsX::POS_ABOVE,
    'encodeLabels' => false,
    'class' => 'tes',
    'pluginOptions' => [
        'bordered' => true,
        'sideways' => true,
        'enableCache' => false
    ],
]);
?>

views/bumdes/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\widgets\SwitchInput;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;

/* @var $this yii\web\View */
/* @var $model app\models\Bumdes */
/* @var $form yii\widgets\ActiveForm */

\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MasalahBumdes', 
        'relID' => 'masalah-bumdes', 
        'value' => \yii\helpers\Json::encode($model->masalahBumdes),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'UnitBumdes', 
        'relID' => 'unit-bumdes', 
        'value' => \yii\helpers\Json::encode($model->unitBumdes),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
?>

<div class="bumdes-form">
    <?php $form = ActiveForm::begin(); ?>
    <div class="card">
        <div class="card-body">

            <?= $form->errorSummary($model); ?>
            <div class="row">
                <div class="col-md-6">


                  <?php $catList = \yii\helpers\ArrayHelper::map(\app\models\Kabupaten::find()->orderBy('nama_kab')->asArray()->all(), 'kd_kab', 'nama_kab') ?>

                  <?= $form->field($model, 'kode_kabupaten')->widget(Select2::classname(), [
                    'data' => $catList,
                    'pluginOptions'=>[
                      'placeholder'=>'Pilih Kabupaten',
                  ],
              ]); ?>

              <?php echo Html::hiddenInput('selected_id', $model->isNewRecord ? '' : $model->kode_kecamatan, ['id'=>'selected_id']); ?>

              <?php 

              $x = \app\models\Kecamatan::find()->where(['kd_kab'=>$model->kode_kabupaten])->all();
                $y=[];
                if ($x!=null) {
                  foreach ($x as $key => $value) {
                    # code...
                  }
                  $y =[
                    $value['kd_kec']=>$value['nama_kec'],
                  ];
                }

              ?>


                  <?=  $form->field($model, 'kode_kecamatan')->widget(DepDrop::classname(), [
                    'type'=>DepDrop::TYPE_SELECT2,
                    'data'=>$y,
                    'options'=>['id'=>'bumdes-kode_kecamatan',],
                    'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
                    'pluginOptions'=>[
                      'depends'=>['bumdes-kode_kabupaten'],
                      'initialize' => true,
                      'url'=>Url::to(['/bumdes/kecamatan']),
                      // 'placeholder'=>'Pilih Kecamatan',
                      'params'=> ['selected_id'], 

                  ]
              ]); ?>


              <!-- $form->field($model, '')->textInput() ?> -->

              <?= $form->field($model, 'nama_bumdes')->textInput(['maxlength' => true]) ?>

              <?= $form->field($model, 'nama_desa')->textInput(['maxlength' => true]) ?>

              <?= $form->field($model, 'alamat')->textarea(['rows' => 6]) ?>

              <?= $form->field($model, 'no_perdes')->textInput(['maxlength' => true]) ?>


              <?= $form->field($model, 'adart')->widget(SwitchInput::classname(), [
                'pluginOptions' => [
                  'onText' => 'Ya',
                  'offText' => 'Tidak',
              ]
          ]) ?>


              <?= $form->field($model, 'rencana_men')->widget(SwitchInput::classname(), [
                'pluginOptions' => [
                  'onText' => 'Ya',
                  'offText' => 'Tidak',
              ]
          ]) ?>

              <?= $form->field($model, 'rencana_th')->widget(SwitchInput::classname(), [
                'pluginOptions' => [
                  'onText' => 'Ya',
                  'offText' => 'Tidak',
              ]
          ]) ?>

              <?= $form->field($model, 'sop')->widget(SwitchInput::classname(), [
                'pluginOptions' => [
                  'onText' => 'Ya',
                  'offText' => 'Tidak',
              ]
          ]) ?>
              <?= $form->field($model, 'catatan_keu')->widget(SwitchInput::classname(), [
                'pluginOptions' => [
                  'onText' => 'Ya',
                  'offText' => 'Tidak',
              ]
          ]) ?>

              <?= $form->field($model, 'status')->widget(SwitchInput::classname(), [
                'pluginOptions' => [
                  'onText' => 'Aktif',
                  'offText' => 'Tidak Aktif',
              ]
          ]) ?>
      </div>

      <div class="col-md-6">
        <?= $form->field($model, 'th_perdes')->textInput() ?>

        <?= $form->field($model, 'jml_omset_th')->textInput() ?>

        <?= $form->field($model, 'kontribusi_pen_desa')->textInput() ?>

        <?= $form->field($model, 'jml_modal')->textInput() ?>

        <?= $form->field($model, 'jml_modal_lain')->textInput() ?>

        <?= $form->field($model, 'jml_kas')->textInput() ?>

        <?= $form->field($model, 'jml_aset_lcr')->textInput() ?>

        <?= $form->field($model, 'jml_aset_ttp')->textInput() ?>

        <?= $form->field($model, 'jml_utang')->textInput() ?>

        <?= $form->field($model, 'jml_utang_bank')->textInput() ?>

        <?= $form->field($model, 'jml_unit_ush')->textInput() ?>

    </div>

    <div class="col-md-12">
      <?php
      $forms = [
        [
            'label' => '<i class="fas fa-book"></i> ' . Html::encode('MasalahBumdes'),
            'content' => $this->render('_formMasalahBumdes', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->masalahBumdes),
            ]),
        ],
        [
            'label' => '<i class="fas fa-book"></i> ' . Html::encode('UnitBumdes'),
            'content' => $this->render('_formUnitBumdes', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->unitBumdes),
            ]),
        ],
    ];
    echo kartik\tabs\TabsX::widget([
        'items' => $forms,
        'position' => kartik\tabs\TabsX::POS_ABOVE,
        'encodeLabels' => false,
        'pluginOptions' => [
            'bordered' => true,
            'sideways' => true,
            'enableCache' => false,
        ],
    ]);
    ?>
</div>

<div class="col-md-12 text-center">
    <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-info']) ?>
    <?= Html::a(Yii::t('app', 'Cancel'), Yii::$app->request->referrer , ['class'=> 'btn btn-secondary']) ?>
</div>

</div>

</div>

</div>
<?php ActiveForm::end(); ?>
</div>

views/bumdes/_formMasalahBumdes.php
<div class="form-group" id="add-masalah-bumdes">
<?php
use kartik\grid\GridView;
use kartik\builder\TabularForm;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\widgets\Pjax;

$dataProvider = new ArrayDataProvider([
    'allModels' => $row,
    'pagination' => [
        'pageSize' => -1
    ]
]);
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'MasalahBumdes',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        'id_masalah' => [
            'label' => 'Tb masalah',
            'type' => TabularForm::INPUT_WIDGET,
            'widgetClass' => \kartik\widgets\Select2::className(),
            'options' => [
                'data' => \yii\helpers\ArrayHelper::map(\app\models\Masalah::find()->orderBy('id_masalah')->asArray()->all(), 'id_masalah', 'nama_masalah'),
                'options' => ['placeholder' => 'Choose Tb masalah'],
            ],
            'columnOptions' => ['width' => '200px']
        ],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return
                    Html::hiddenInput('Children[' . $key . '][id]', (!empty($model['id'])) ? $model['id'] : "") .
                    Html::a('<i class="fas fa-trash"></i>', '#', ['title' =>  'Delete', 'onClick' => 'delRowMasalahBumdes(' . $key . '); return false;', 'id' => 'masalah-bumdes-del-btn']);
            },
        ],
    ],
    'gridSettings' => [
        'panel' => [
            'heading' => false,
            'type' => GridView::TYPE_DEFAULT,
            'before' => false,
            'footer' => false,
            'after' => Html::button('<i class="fas fa-plus"></i>' . 'Add Masalah Bumdes', ['type' => 'button', 'class' => 'btn btn-success kv-batch-create', 'onClick' => 'addRowMasalahBumdes()']),
        ]
    ]
]);
echo  "    </div>\n\n";
?>

views/bumdes/_formUnitBumdes.php
<div class="form-group" id="add-unit-bumdes">
<?php
use kartik\grid\GridView;
use kartik\builder\TabularForm;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\widgets\Pjax;

$dataProvider = new ArrayDataProvider([
    'allModels' => $row,
    'pagination' => [
        'pageSize' => -1
    ]
]);
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'UnitBumdes',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        'id_unit' => [
            'label' => 'Tb unit',
            'type' => TabularForm::INPUT_WIDGET,
            'widgetClass' => \kartik\widgets\Select2::className(),
            'options' => [
                'data' => \yii\helpers\ArrayHelper::map(\app\models\Unit::find()->orderBy('id_unit')->asArray()->all(), 'id_unit', 'nama_unit'),
                'options' => ['placeholder' => 'Choose Tb unit'],
            ],
            'columnOptions' => ['width' => '200px']
        ],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return
                    Html::hiddenInput('Children[' . $key . '][id]', (!empty($model['id'])) ? $model['id'] : "") .
                    Html::a('<i class="fas fa-trash"></i>', '#', ['title' =>  'Delete', 'onClick' => 'delRowUnitBumdes(' . $key . '); return false;', 'id' => 'unit-bumdes-del-btn']);
            },
        ],
    ],
    'gridSettings' => [
        'panel' => [
            'heading' => false,
            'type' => GridView::TYPE_DEFAULT,
            'before' => false,
            'footer' => false,
            'after' => Html::button('<i class="fas fa-plus"></i>' . 'Add Unit Bumdes', ['type' => 'button', 'class' => 'btn btn-success kv-batch-create', 'onClick' => 'addRowUnitBumdes()']),
        ]
    ]
]);
echo  "    </div>\n\n";
?>

views/bumdes/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

views/bumdes/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BumdesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-bumdes-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php // $form->field($model, 'id_bumdes')->textInput(['placeholder' => 'Id Bumdes']) ?>

    <?php //$form->field($model, 'kode_bumdes')->textInput(['maxlength' => true, 'placeholder' => 'Kode Bumdes']) ?>

    <?= $form->field($model, 'nama_bumdes')->textInput(['maxlength' => true, 'placeholder' => 'Nama Bumdes']) ?>

    <?= $form->field($model, 'nama_desa')->textInput(['maxlength' => true, 'placeholder' => 'Nama Desa']) ?>

    <?= $form->field($model, 'alamat')->textarea(['rows' => 6]) ?>

    <?php /* echo $form->field($model, 'no_perdes')->textInput(['maxlength' => true, 'placeholder' => 'No Perdes']) */ ?>

    <?php /* echo $form->field($model, 'th_perdes')->textInput(['placeholder' => 'Th Perdes']) */ ?>

    <?php /* echo $form->field($model, 'adart')->checkbox() */ ?>

    <?php /* echo $form->field($model, 'rencana_men')->checkbox() */ ?>

    <?php /* echo $form->field($model, 'rencana_th')->checkbox() */ ?>

    <?php /* echo $form->field($model, 'sop')->checkbox() */ ?>

    <?php /* echo $form->field($model, 'catatan_keu')->checkbox() */ ?>

    <?php /* echo $form->field($model, 'jml_omset_th')->textInput(['placeholder' => 'Jml Omset Th']) */ ?>

    <?php /* echo $form->field($model, 'kontribusi_pen_desa')->textInput(['placeholder' => 'Kontribusi Pen Desa']) */ ?>

    <?php /* echo $form->field($model, 'jml_modal')->textInput(['placeholder' => 'Jml Modal']) */ ?>

    <?php /* echo $form->field($model, 'jml_modal_lain')->textInput(['placeholder' => 'Jml Modal Lain']) */ ?>

    <?php /* echo $form->field($model, 'jml_kas')->textInput(['placeholder' => 'Jml Kas']) */ ?>

    <?php /* echo $form->field($model, 'jml_aset_lcr')->textInput(['placeholder' => 'Jml Aset Lcr']) */ ?>

    <?php /* echo $form->field($model, 'jml_aset_ttp')->textInput(['placeholder' => 'Jml Aset Ttp']) */ ?>

    <?php /* echo $form->field($model, 'jml_utang')->textInput(['placeholder' => 'Jml Utang']) */ ?>

    <?php /* echo $form->field($model, 'jml_utang_bank')->textInput(['placeholder' => 'Jml Utang Bank']) */ ?>

    <?php /* echo $form->field($model, 'jml_unit_ush')->textInput(['placeholder' => 'Jml Unit Ush']) */ ?>

    <?php /* echo $form->field($model, 'status')->textInput(['placeholder' => 'Status']) */ ?>

    <?php /* echo $form->field($model, 'kode_kabupaten')->textInput(['maxlength' => true, 'placeholder' => 'Kode Kabupaten']) */ ?>

    <?php /* echo $form->field($model, 'kode_kecamatan')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\models\TbKecamatan::find()->orderBy('kd_kec')->asArray()->all(), 'kd_kec', 'kd_kec'),
        'options' => ['placeholder' => 'Choose Tb kecamatan'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); */ ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/bumdes/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Bumdes */

$this->title = 'Create Bumdes';
$this->params['breadcrumbs'][] = ['label' => 'Bumdes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bumdes-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>